// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-income-records.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_income_records_default = defineTool({
  name: "list_income_records",
  title: "Lijst inkomsten-records",
  description: "Haal inkomsten-records op voor de ingelogde arts. Filter optioneel op jaar, maand en/of income_type (Ambulant of Gehospitaliseerd).",
  inputSchema: {
    year: z.number().int().min(2e3).max(2100).optional().describe("Filter op jaar"),
    month: z.number().int().min(1).max(12).optional().describe("Filter op maand (1-12)"),
    income_type: z.enum(["Ambulant", "Gehospitaliseerd"]).optional(),
    limit: z.number().int().min(1).max(500).default(100).describe("Max aantal rijen")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, month, income_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    let q = client(ctx).from("income_records").select("id, record_date, year, month, income_type, nomenclature_code, description, quantity, unit_amount, total_amount, aandeel_arts, mif, bouwfonds, netto").order("record_date", { ascending: false }).limit(limit ?? 100);
    if (year != null) q = q.eq("year", year);
    if (month != null) q = q.eq("month", month);
    if (income_type) q = q.eq("income_type", income_type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/income-summary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var income_summary_default = defineTool2({
  name: "income_summary",
  title: "Inkomsten samenvatting",
  description: "Bereken totalen (bruto, aandeel arts, MIF, bouwfonds, netto) per income_type voor een jaar of specifieke maand.",
  inputSchema: {
    year: z2.number().int().min(2e3).max(2100).describe("Jaar"),
    month: z2.number().int().min(1).max(12).optional().describe("Optionele maand")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, month }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    let q = client2(ctx).from("income_records").select("income_type, total_amount, aandeel_arts, mif, bouwfonds, netto").eq("year", year);
    if (month != null) q = q.eq("month", month);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const totals = {};
    for (const r of data ?? []) {
      const t = totals[r.income_type] ??= { count: 0, total_amount: 0, aandeel_arts: 0, mif: 0, bouwfonds: 0, netto: 0 };
      t.count += 1;
      t.total_amount += Number(r.total_amount ?? 0);
      t.aandeel_arts += Number(r.aandeel_arts ?? 0);
      t.mif += Number(r.mif ?? 0);
      t.bouwfonds += Number(r.bouwfonds ?? 0);
      t.netto += Number(r.netto ?? 0);
    }
    const summary = { year, month: month ?? null, by_income_type: totals };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-nomenclature.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_nomenclature_default = defineTool3({
  name: "list_nomenclature",
  title: "Lijst RIZIV-nomenclatuurcodes",
  description: "Haal de nomenclatuurcodes van de arts op, optioneel gefilterd op categorie of code.",
  inputSchema: {
    category: z3.string().optional(),
    code: z3.string().optional().describe("Filter op exacte code"),
    limit: z3.number().int().min(1).max(1e3).default(500)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, code, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    let q = client3(ctx).from("nomenclature_codes").select("id, code, description, category, netto_amount").order("code").limit(limit ?? 500);
    if (category) q = q.eq("category", category);
    if (code) q = q.eq("code", code);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-goals.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_goals_default = defineTool4({
  name: "list_goals",
  title: "Lijst doelstellingen",
  description: "Haal inkomstendoelen (jaar/kwartaal/maand) van de arts op, optioneel gefilterd op jaar.",
  inputSchema: {
    year: z4.number().int().min(2e3).max(2100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    let q = client4(ctx).from("income_goals").select("id, year, period_type, period_value, period_start, period_end, income_type, metric, amount, note").order("year", { ascending: false }).order("sort_order");
    if (year != null) q = q.eq("year", year);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-portfolio.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_portfolio_default = defineTool5({
  name: "list_portfolio_assets",
  title: "Lijst beursportfolio",
  description: "Haal aandelen/ETF posities uit de portfolio van de arts op.",
  inputSchema: {
    symbol: z5.string().optional().describe("Filter op ticker")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    let q = client5(ctx).from("portfolio_assets").select("id, symbol, name, asset_type, exchange, mic, currency, quantity, purchase_price, purchase_date, notes").order("symbol");
    if (symbol) q = q.eq("symbol", symbol.toUpperCase());
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-pension.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
function client6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pension_default = defineTool6({
  name: "list_pension_records",
  title: "Lijst pensioen-snapshots",
  description: "Haal pensioen- en IPT-snapshots op. Kies bron 'pension' (VAPZ/hoofdcontract) of 'ipt' (IPT).",
  inputSchema: {
    source: z6.enum(["pension", "ipt"]).default("pension"),
    year: z6.number().int().min(1990).max(2100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ source, year }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    const sb = client6(ctx);
    const table = source === "ipt" ? "pension_ipt_records" : "pension_records";
    let q = sb.from(table).select("*").order("snapshot_date", { ascending: false });
    if (year != null) q = q.eq("year", year);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ftsgbacnewhpzasrjmrs";
var mcp_default = defineMcp({
  name: "medincome-mcp",
  title: "MedIncome",
  version: "0.1.0",
  instructions: "Read-only toegang tot MedIncome-data van de ingelogde arts: inkomsten-records en samenvattingen, RIZIV-nomenclatuur, doelstellingen, pensioen/IPT snapshots en beursportfolio. Alle bedragen in EUR, taal Nederlands (nl-BE).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_income_records_default, income_summary_default, list_nomenclature_default, list_goals_default, list_portfolio_default, list_pension_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
