// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const missingSupabaseConfig = [
  !SUPABASE_URL ? 'VITE_SUPABASE_URL' : null,
  !SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
].filter(Boolean) as string[];

export const isSupabaseConfigured = missingSupabaseConfig.length === 0;
const authStorage = typeof window !== 'undefined' ? window.sessionStorage : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://missing-supabase-url.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'missing-supabase-publishable-key',
  {
    auth: {
      ...(authStorage ? { storage: authStorage } : {}),
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
